skypjack/uvw

test/uvw/async.cpp
test/uvw/check.cpp
test/uvw/idle.cpp
test/uvw/loop.cpp
test/uvw/prepare.cpp
test/uvw/signal.cpp
test/uvw/timer.cpp

GoogleTest defines a `FAIL` macro which is a concise way of making an assert failure.
<br />Note that these assertion failures (in lambda expressions) are non-fatal unlike their usual usage.

Tests concise GoogleTest assertion failures

---

.travis.yml

Added the code coverage reporting and integrated with [coveralls.io](https://coveralls.io/) for visualizing and tracking the coverage numbers. [Here](https://coveralls.io/builds/8234660) is a sample report from the test build.
<br />* Reorganized the Travis configuration to streamline adding new builds/tool-chains later on.
<br />* Added the new jobs in travis:
<br /> - `g++-6` for Linux
<br /> - `xcode8` for macOS
<br />
<br />Left the badge for `README.md` to be added later.

Code coverage using coveralls.io

---

src/uvw/stream.hpp
src/uvw/udp.hpp
test/uvw/loop.cpp

Also contains a commit to get the code coverage back to the old value: added a statement to `ASSERT` the pointer to default loop returned is the same on the second call to `Loop::getDefault`.

Replaced `for` loop as mentioned in comment

---

src/uvw/emitter.hpp

We are inserting callbacks to the front of  `onL` and `onceL` lists, but we invoke those callbacks from the `begin()` towards the `end()` of the lists; if we want still to insert callbacks to the front, we should use `rbegin()` and `rend()`, but I think we can safely insert callbacks to the back.

insert callbacks to the back, so that will be invoked in the proper order

---

src/uvw/dns.hpp
src/uvw/fs.hpp
src/uvw/loop.hpp
src/uvw/request.hpp

A continuation of PR #61.
The changes reduce the number of times `uv_*_t` identifiers occur in `uvw` code further. This focuses on the Request hierarchy (the Handle hierarchy was covered in the previous PR).
Also, made the change agreed upon in [this comment](https://github.com/skypjack/uvw/commit/2838f6e239cbefa68e900e55760e20660f5fa73e#commitcomment-19736512).

Cleanup further

---

src/uvw/stream.hpp

There is no reason to force client code to get read data as an `std::unique_ptr<const char[]>`, and I would change the type of `DataEvent::data` to `std::unique_ptr<char[]>` for two reasons:
- I think it's up to the user whether he wants those data to be modifiable or not
- this way, I could use data received in a `DataEvent` as an argument for `StreamHandle::write()`; on the other hand, if `DataEvent::data` is a _pointer to const_, if I want to write those data through a `StreamHandle` I'm forced to perform an avoidable copy
As a side note: it would be great if the `StreamHandle::write()` function would accept _pointer to const_ as a data argument, but I've not been able to find any guarantee in _libuv_ documentation that those buffer will not be modified by the write (as it should be), …

made DataEvent::data unique_ptr non-const

---

src/uvw/fs.hpp
src/uvw/stream.hpp
src/uvw/udp.hpp

It does make sense to me that `ssize_t` does not even appear in `uvw` interfaces; this way, ctors can use _uniform initialization_ to initialize `length`'s member variables (thus requiring diagnostic for narrowing conversions, if I'm not wrong), and explicit casts are performed where they belongs to, inside the implementation, where you have just checked that the variable you are casting from `ssize_t` to `std::size_t` is `>=0`.

replaced ssize_t with std::size_t in ctors

---

src/uvw/udp.hpp

Missing const fails to compile the code with a build error.

Fix build failure when using UDPHandle::recv()

---

src/uvw/udp.hpp

Fix a warning with GCC/Linux and a build error with Clang/macOS.
```
udp.hpp:111:82: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'std::size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
note: insert an explicit cast to silence this issue
udp.hpp:111:89: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'bool' in initializer list [-Wc++11-narrowing]
note: insert an explicit cast to silence this issue
udp.hpp:116:82: error: non-constant-expression cannot be narrowed from type 'ssize_t' (aka 'long') to 'std::size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
note: insert an explicit cast to silence this issue
```

Fix -Wc++11-narrowing error/warning

---

src/uvw/process.hpp

If po.cwd is set to an empty string the process failed to start with an error.

uv_spawn: Do not set cwd to an empty string

---

src/uvw/dns.hpp
src/uvw/emitter.hpp
src/uvw/fs.hpp
src/uvw/fs_event.hpp
src/uvw/fs_poll.hpp
src/uvw/poll.hpp
src/uvw/stream.hpp
src/uvw/tcp.hpp
src/uvw/udp.hpp
src/uvw/util.hpp

GCC is spawning a lot of warnings about shadowed parameters. This PR fixes all of those.
Renamed shadowed members errors like:
`warning: declaration of ‘path’ shadows a member of ‘uvw::FsEvent<(uvw::details::UVFsType)10>’ [-Wshadow]`

Fix GCC warnings -Wshadow

---

src/uvw/lib.hpp
src/uvw/resource.hpp
src/uvw/resource_base.hpp
src/uvw/thread.hpp
src/uvw/underlying_type.hpp

The advantage of having a common `create` method is that it consolidates the dynamic allocation of "resources" in `uvw`. This doesn't exhaust all instances, but reduces the usage of `new` in existing code.
An observable benefit of the change is the reduction of duplicate arguments to the `create` method and the class constructors.
**Change description:**
Consolidate the `<Type>::create` methods from various classes - `SharedLib`, `Thread` and others in a single base class. Also aggregate other similar functionality like getting the owning `Loop` object reference, getting the owned libuv structure pointer.
Since `class Resource` inherits `Emitter` and `std::enable_shared_from_this`, it isn't a feasible option. Therefore, `ResourceBase` (the name can be decided upon) is extracted from and …

Common create method

---

src/uvw/stream.hpp
src/uvw/udp.hpp

There may be a better way to access member variables from the underlying libuv types but I'm not sure how to do it.

FEATURE: expose write_queue_size

---

CMakeLists.txt

Cross compilation for Jetson board was failing with:
CMake Error at /usr/local/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
/usr/local/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
/usr/local/share/cmake-3.11/Modules/FindThreads.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:64 (find_package)

Fix cross-compilation

---

.conan/build.py
.conan/test_package/CMakeLists.txt
.conan/test_package/conanfile.py
.conan/test_package/test_package.cpp
.gitignore
.travis.yml
README.md
conanfile.py

Hi!
This PR brings the support for Conan.
Including:
- .conan/build.py
Build script to create Conan package on Travis CI
- .conan/test_package/CMakeLists.txt
CMake file to build test package
- .conan/test_package/conanfile.py
Conan recipe to build test package
- .conan/test_package/test_package.cpp
Example code to consume Conan package created
- .travis.yml
Update to run Conan job on CI
- conanfile.py
Conan recipe to provide UVM package
- bintray badge on README
Download link page for UVM package
Conan uses the file *conanfile.py* as recipe to execute all steps necessary to create the package. As your project is header-only it doesn't need build anything, just copy all headers and license. Conan defines the package id by settings + options and UVW is header-only so it doesn't need set …

#135 Conan package support

---

AUTHORS
README.md

I assumed the updates are closer to the intended meaning, but I'm happy to amend this pull request if I've misunderstood some things.

update typos and ambiguous phrases in README

---

src/uvw/fs.hpp

I believe it was a small typo in the method name, as uv does name it uv_fs_statfs and the method name in Linux is also statfs

Changed FsReq::stasfs method name to statfs

---

src/uvw/handle.hpp
src/uvw/resource.hpp

Today, uvw triggers undefined behavior in resource.hpp:
```
runtime error: downcast of address which does not point to an object of type 'uvw::FsEventHandle'
note: object is of type 'uvw::BaseHandle'
```
It looks like we're saving the current handle in the void* data member
so it can be retrieved on the next callback run. This downcast to a
derived class from its parents ctor as it's being constructed isn't
well defined.
Since we're storing this as a void* anyways and all the callsites using
it need to do their own cast on retrieval, we can instead persist the
this pointer. For downcasting to work in all cases the Resource class
tree needs to be leftmost in Handler's multiple inheritance.
Tested by verifying that my unit tests no longer show ubsan errors and
uvw's test suite still passes.

fix undefined behavior in resource.hpp

---

src/uvw/handle.hpp
test/CMakeLists.txt
test/uvw/file_req.cpp
test/uvw/file_req_sendfile.cpp
test/uvw/handle.cpp

Renames fileno() so it doesn't clash with OpenBSD's macro expansion.
Makes minor changes to build steps so the test suite compiles and runs
on OpenBSD.
See https://github.com/skypjack/uvw/issues/201 for full context

add openbsd support

---

CMakeLists.txt
src/CMakeLists.txt

- CMake package config files for uvw, they are now installed as ${LIBDIR}/cmake/uvw/uvwConfig.cmake with target files for appropriate configuration (e.g. debug, release, etc...).
- A `uvw::uvw` ALIAS target is created for uvw static library, to make persistency with what is done to the header-only version,
Callers can now use `find_package(uvw)` and link with the `uvw::uvw` target to use uvw in their projects directly using CMake.

+ improve CMake-based package config files.

---

CMakeLists.txt

(Otherwise, the caller will receive an error like:
```
CMake Error in CMakeLists.txt:
export called with target "..." which requires target "uvw" that is
not in any export set.
```

export `uvwConfig` to build a uvw submodule statically

---

src/uvw/emitter.h
src/uvw/thread.h
src/uvw/timer.h
src/uvw/type_info.hpp
src/uvw/util.h

Use namespaced version of stdint.h header, which defines int32_t, uint32_t and similar types.
This fixes build error when building flamethrower package with recent release of uvw.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2171490

Include cstdint where uintX_t is used

---

README.md

I'm the author of [vcpkg.link](https://vcpkg.link) and currently trying to improve the discoverability of Vcpkg ports since it helps other developers to integrate libraries into their projects.
This PR aims to add a fresh new [shields.io](https://shields.io) badge (https://github.com/badges/shields/pull/8923) that provides at a glance in the README which version of uvw is available on [Vcpkg](https://vcpkg.link/ports/uvw).

Add Vcpkg badge

---

.gitignore
CMakeLists.txt

[cmake] CMake Error at CMakeLists.txt:190 (set_target_properties):
[cmake]   INTERFACE_LIBRARY targets may only have whitelisted properties.  The
[cmake]   property "VERSION" is not allowed.

avoid cmake complaining about using VERSION keyword

---

test/uvw/util.cpp

Some architectures do not have implemented obtaining cpu speed. They return 0 for undefined value. Pass the test with any non-negative value.
Resolves #252

Do not fail unit test because cpu speed 0

---

src/uvw/poll.cpp
src/uvw/poll.h

The line 
```
using poll_event = details::uvw_poll_event;
```
created an ambiguous alias with the same name as the  `struct poll_event`.
And `poll_handle` should be inheriting `handle<poll_handle, uv_poll_t, poll_event>` instead of `handle<poll_handle, uv_poll_t, details::uvw_poll_event>` if I'm understanding correctly. Otherwise `on<uvw::poll_event>()` doesn't work.

Fix compile errors caused by ambiguous naming of poll_event in poll_handle

---

src/uvw/process.cpp

Hello, the same problem as #278 
Starting with c++20, comparison operators can now be reversed and lead to ambiguous overloads. (cf https://brevzin.github.io/c++/2019/07/28/comparisons-cpp20/#reversing-primary-operators, https://stackoverflow.com/questions/65946930/ambiguous-overloaded-operator-c20)
An minimal reproductive example: https://godbolt.org/z/jTP469TMf
Fix it with an explicit type conversion
relative issue from an other project: https://github.com/boostorg/date_time/issues/132

fix ambiguous overloaded from c++20 with explicit cast

---

src/uvw/loop.h

Fixes the following compiler `-Wshadow` warning by renaming a variable:
```
In file included from /uvw/src/uvw/fs.h:11,
from /uvw/test/uvw/file_req_sendfile.cpp:3:
/uvw/src/uvw/loop.h: In lambda function:
/uvw/src/uvw/loop.h:281:49: warning: declaration of ‘func’ shadows a previous local [-Wshadow]
281 |         auto func = [](uv_handle_t *hndl, void *func) {
|                                           ~~~~~~^~~~
/home/alois/Documents/uvw/src/uvw/loop.h:281:14: note: shadowed declaration is here
281 |         auto func = [](uv_handle_t *hndl, void *func) {
|              ^~~~
```

loop: rename variable to fix `-Wshadow` warning

---

src/uvw/uv_type.hpp

The `uv_type()` constructor does not use its `token` parameter, which causes a `-Werror=unused` compiler error on GCC (and probably on other compilers too).
~Luckily, C++17 adds the [`[[maybe_unused]]`][1] attribute that all standards compliant compilers will support to hide unused errors.~ Removed, see https://github.com/skypjack/uvw/pull/296#issuecomment-1686169140.
[1]: https://en.cppreference.com/w/cpp/language/attributes/maybe_unused
---
This fixes the error reported in https://github.com/skypjack/uvw/issues/294#issuecomment-1683625763, but I didn't want to add a `Fixes: #294` into my commit or PR, since it seems like that issue is more about disabling all potential warnings using CMake, not just this single error.

uv_type: supress `-Werror=unused` compiler error

---

src/uvw/tty.cpp

There's an unneeded semi-colon after the definition of `tty_handle::mode_memo_handler()` that may cause a compiler to print a warning:
This no longer seems to appear on newer G++ compilers, only older ones (like GCC-10).
```
In file included from /home/runner/work/uvw/uvw/src/uvw/tty.h:143,
from /home/runner/work/uvw/uvw/src/uvw.hpp:24,
from /home/runner/work/uvw/uvw/test/main.cpp:5:
/home/runner/work/uvw/uvw/src/uvw/tty.cpp:25:2: error: extra ‘;’ [-Werror=pedantic]
25 | };
```
Logs taken from https://github.com/aloisklink/uvw/actions/runs/5952382537/job/16144246200
```
/home/runner/work/uvw/uvw/src/uvw/tty.cpp:25:2: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
};
```

tty: remove unnecessary semi-colon

---

src/uvw/type_info.hpp

On GCC 7.5.0, the current `uvw::internal::fnv1a()` function throws a `-Wsign-conversion` warning, despite us having an explicit cast.
```
src/uvw/type_info.hpp: In function 'constexpr uint32_t uvw::internal::fnv1a(const char*)':
src/uvw/type_info.hpp:24:26: warning: conversion to 'unsigned int' from 'char' may change the sign of the result [-Wsign-conversion]
value = (value ^ static_cast<std::uint32_t>(curr_val)) * prime;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This seems to be a bug in GCC 7.5.0, since newer versions of GCC are fine with it (including GCC 8). Moving the cast to another line fixes the warning, and it should all be compiled down to the same machine code anyway.

type_info: avoid gcc-7 `-Wsign-conversion warning`

---

src/uvw/pipe.cpp

Hide the following `-Wsign-conversion` warning in `uvw::pipe_handle::connect()` by explicitly passing an `unsigned int`.
```
/uvw/src/uvw/stream.h:56:48: warning: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
56 |         return this->leak_if(std::forward<F>(f)(raw(), std::forward<Args>(args)..., &connect_callback));
```

pipe: hide `uvw::pipe_handle::connect()` `-Wsign-conversion` warning

---

src/uvw/util.cpp

Explicitly cast `unsigned int port` to an `signed int` to supress a `-Wsign-conversion` warning in `uvw::details::ip_addr()`.
We don't need to worry about too much about overflowing, since `libuv` internally just converts everything back to an `unsigned short` later, see https://github.com/libuv/libuv/blob/b3759772d20e89537980d5d43a01ce4c2f2535a8/src/uv-common.c#L257
```
/uvw/src/uvw/util.cpp: In function ‘sockaddr uvw::details::ip_addr(const char*, unsigned int)’:
/uvw/src/uvw/util.cpp:63:47: warning: conversion to ‘int’ from ‘unsigned int’ may change the sign of the result [-Wsign-conversion]
63 |     if(sockaddr_in addr_in; uv_ip4_addr(addr, port, &addr_in) == 0) {
|                                               ^~~~
/uvw/src/uvw/util.cpp:65:56: warning: conversion to ‘int’ from …
```

util: fix `-Wsign-conversion` in ip_addr()

---

src/uvw/uv_type.hpp

Make the destructor for `uv_type` `protected`, in order to the fix the `-Wnon-virtual-dtor` warnings:
```
‘struct uvw::uv_type<uv_async_s>’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
```
This prevents a potential memory leak when calling the `~uv_type()` destructor (instead of the `~resource()` destructor) on a `uvw::resource`.
As an example, the code below currently works (casting a pointer to a subclass of `uvw::uv_type` to `uvw::uv_type`, but it causes a memory leak, since only the `uvw::uv_type` destructor is called. Doing this is now forbidden.
```c++
uvw::resource<...>* will_leak;
auto abc = std::unique_ptr<uvw::uv_type>(will_leak);
```
---
**BREAKING CHANGE**: This change may break the `uvw` ABI, since we're changing the destructor from …

uv_type: make `~uv_type()` destructor protected

---

test/main.cpp
test/uvw/fs_req.cpp
test/uvw/loop.cpp
test/uvw/thread.cpp

Fixes a couple of compiler warnings in the test directory.
Since the `test` directory doesn't affect users, I've just made a single PR that includes all my changes. But please let me know if you'd prefer to break my changes up into smaller PRs (I've tried to split up each change into individual commits, to make it a bit easier to review!)

Fix compiler warnings in `test` directory

---

.github/workflows/build-ubuntu-20.04.yml
.github/workflows/build-ubuntu-latest.yml
CMakePresets.json

Add a [`CMakePresets.json`][1] file that contains `ci-ubuntu` preset. This preset contains most of the recommended compiler warnings from the [`cmake-init`][2] project, with the following changes:
- I had to remove the `-Wdouble-promotion` and `-Werror=float-equal` flags since there are issues within the GTest headers.
- For compatibility with g++-7, which doesn't support this flag, `-Wextra-semi` was removed.
- I also had to remove some of the following flags like: `-fstack-protector-strong -fstack-clash-protection`. These flags cause errors in Clang v10, and to be honest, with stuff like address sanitizer, we probably don't need them.
I've also set the `"CMAKE_CXX_FLAGS_DEBUG": "-Werror"` variable when running on `ubuntu` in GitHub Actions. This will make the `ubuntu` build fail …

Check for GCC/Clang compiler warnings in Ubuntu GitHub Actions CI

---

.github/workflows/build-meson.yml
README.md
meson.build
subprojects/.gitignore
subprojects/libuv.wrap

This PR adds initial support for the [meson](https://mesonbuild.com/) build system. Currently set up to work as a shared/static library, since that works best with meson's dependency system for libuv.
This should be able to be backported to the current release as well if desired.

build: add initial meson support

---

README.md
meson.build
subprojects/libuv.wrap

- ran `meson wrap update` to update subproject version
- updated meson.build to reflect new version number

build(meson): bump libuv to 1.48.0
